name: Verify

on:
    push:
        branches: main
    pull_request:
        branches: main

jobs:
    build:
        name: Verify
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v7

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: npm

            - run: npm install --global yarn
            - run: yarn set version 3.2.0
            - run: yarn install
            - run: yarn workspace @project/extension run zip
            - run: yarn workspace @project/client run build

